<?php
/* @var $helper Driveback_DigitalDataLayer_Helper_Data */
$helper = $this->helper('driveback_ddl');

$ddl = $helper->getDdl();
?>

<?php if ($helper->digitalDataLayerEnabled()): ?>
    <script type="text/javascript">
        (function () {
            var digitalDataTemp = <?php echo $ddl->getDigitalData(); ?>;
            window.digitalData = $H(window.digitalData || {}).merge(digitalDataTemp).toObject();
        })();
    </script>
<?php endif;?>
<?php if ($helper->digitalDataManagerEnabled()): ?>
    <script type="text/javascript">
        (function() {
            var a = window.ddManager = window.ddManager || [];
            window.ddListener = window.ddListener || [];
            var b = window.digitalData = window.digitalData || {};
            b.events = b.events || [];
            if (!a.initialize) {
                if (a.invoked) {
                    window.console && console.error && console.error("Digital Data Manager snippet included twice.");
                } else {
                    a.invoked = !0;
                    a.methods = ["initialize", "addIntegration", "on", "once", "off"];
                    a.factory = function(b) {
                        return function() {
                            var c = Array.prototype.slice.call(arguments);
                            c.unshift(b);
                            a.push(c);
                            return a;
                        };
                    };
                    for (b = 0;b < a.methods.length;b++) {
                        var d = a.methods[b];
                        a[d] = a.factory(d);
                    }
                    a.load = function() {
                        var a = document.createElement("script");
                        a.type = "text/javascript";
                        a.async = !0;
                        a.src = "/js/driveback/dd-manager.min.js";
                        var b = document.getElementsByTagName("script")[0];
                        b.parentNode.insertBefore(a, b);
                    };
                    a.SNIPPET_VERSION = "1.0.1";
                    a.load();
                }
            }
        })();
    </script>
<?php endif;?>
