<?php
/* @var $helper Driveback_DigitalDataLayer_Helper_Data */
$helper = $this->helper('driveback_ddl');

$ddl = $helper->getDdl();
?>

<?php if ($helper->digitalDataLayerEnabled()): ?>
    <script type="text/javascript">
        (function () {
            var digitalDataTemp = <?php echo $ddl->getDigitalData(); ?>;
            window.digitalData = $H(window.digitalData || {}).merge(digitalDataTemp).toObject();
        })();
    </script>
<?php endif;?>
<?php if ($helper->digitalDataManagerEnabled()): ?>
    <script type="text/javascript" src="/js/driveback/dd-manager.min.js" async defer></script>
<?php endif;?>
